CODE_FIRST/Models/ErrorViewModel.cs
namespace CODE_FIRST.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CODE_FIRST/Models/KHOA.cs
namespace CODE_FIRST.Models
{
    public class KHOA
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

CODE_FIRST/Models/LOP.cs
namespace CODE_FIRST.Models
{
    public class LOP
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

CODE_FIRST/Models/SINHVIEN.cs
namespace CODE_FIRST.Models
{
    public class SINHVIEN
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public DateOnly? DoB { get; set; }
        public string? lopId { get; set; }
        public string? khoaId { get; set; }
    }
}

CODE_FIRST/Controllers/HomeController.cs
using CODE_FIRST.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CODE_FIRST.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CODE_FIRST/Controllers/SinhviensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CODE_FIRST.Data;
using CODE_FIRST.Models;

namespace CODE_FIRST.Controllers
{
    public class SinhviensController : Controller
    {
        private readonly SinhviensContext _context;

        public SinhviensController(SinhviensContext context)
        {
            _context = context;
        }

        // GET: Sinhviens
        public async Task<IActionResult> Index()
        {
            return View(await _context.SINHVIEN.ToListAsync());
        }

        // GET: Sinhviens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sINHVIEN = await _context.SINHVIEN
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sINHVIEN == null)
            {
                return NotFound();
            }

            return View(sINHVIEN);
        }

        // GET: Sinhviens/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sinhviens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DoB,lopId,khoaId")] SINHVIEN sINHVIEN)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sINHVIEN);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sINHVIEN);
        }

        // GET: Sinhviens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sINHVIEN = await _context.SINHVIEN.FindAsync(id);
            if (sINHVIEN == null)
            {
                return NotFound();
            }
            return View(sINHVIEN);
        }

        // POST: Sinhviens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DoB,lopId,khoaId")] SINHVIEN sINHVIEN)
        {
            if (id != sINHVIEN.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sINHVIEN);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SINHVIENExists(sINHVIEN.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sINHVIEN);
        }

        // GET: Sinhviens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sINHVIEN = await _context.SINHVIEN
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sINHVIEN == null)
            {
                return NotFound();
            }

            return View(sINHVIEN);
        }

        // POST: Sinhviens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sINHVIEN = await _context.SINHVIEN.FindAsync(id);
            if (sINHVIEN != null)
            {
                _context.SINHVIEN.Remove(sINHVIEN);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SINHVIENExists(int id)
        {
            return _context.SINHVIEN.Any(e => e.Id == id);
        }
    }
}

CODE_FIRST/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CODE_FIRST/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CODE_FIRST</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CODE_FIRST.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CODE_FIRST</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sinhviens" asp-action="Index">Sinh viên</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CODE_FIRST - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CODE_FIRST/Views/Sinhviens/Create.cshtml
@model CODE_FIRST.Models.SINHVIEN

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SINHVIEN</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoB" class="control-label"></label>
                <input asp-for="DoB" class="form-control" />
                <span asp-validation-for="DoB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lopId" class="control-label"></label>
                <input asp-for="lopId" class="form-control" />
                <span asp-validation-for="lopId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="khoaId" class="control-label"></label>
                <input asp-for="khoaId" class="form-control" />
                <span asp-validation-for="khoaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CODE_FIRST/Views/Sinhviens/Delete.cshtml
@model CODE_FIRST.Models.SINHVIEN

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SINHVIEN</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lopId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lopId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.khoaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.khoaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CODE_FIRST/Views/Sinhviens/Details.cshtml
@model CODE_FIRST.Models.SINHVIEN

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SINHVIEN</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DoB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DoB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lopId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lopId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.khoaId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.khoaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CODE_FIRST/Views/Sinhviens/Edit.cshtml
@model CODE_FIRST.Models.SINHVIEN

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SINHVIEN</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoB" class="control-label"></label>
                <input asp-for="DoB" class="form-control" />
                <span asp-validation-for="DoB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lopId" class="control-label"></label>
                <input asp-for="lopId" class="form-control" />
                <span asp-validation-for="lopId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="khoaId" class="control-label"></label>
                <input asp-for="khoaId" class="form-control" />
                <span asp-validation-for="khoaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CODE_FIRST/Views/Sinhviens/Index.cshtml
@model IEnumerable<CODE_FIRST.Models.SINHVIEN>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách sinh viên</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.lopId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.khoaId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lopId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.khoaId)
            </td>
            <td>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>